#ifndef ENUMS_H
#define ENUMS_H

enum VertexNames { V0, V1, V2, V3 };
enum EdgeNames { E0, E1, E2, E3 };
enum RegionNames { STRONG_IDENTIFICATION, IDENTIFICATION, RECOGNITION, OBSERVATION, DETECTION, MONITORING, DEAD_ZONE };
#endif // ENUMS_H
